[project]
name = "odoo-addons-oca-manufacture-reporting"
version = "18.0.20241204.0"
dependencies = [
    "odoo-addon-mrp_flattened_bom_xlsx==18.0.*",
]
classifiers=[
    "Programming Language :: Python",
    "Framework :: Odoo",
    "Framework :: Odoo :: 18.0",
]
